<?php
/**
 * This file declare the PluginSfGaufretteValidatedFile class.
 *
 * @package sfGaufrettePlugin
 * @subpackage lib.validator.plugin
 * @author Julien Muetton <julien_muetton@carpe-hora.com>
 * @copyright (c) Carpe Hora SARL 2012
 * @since 2012-01-26
 */

/**
 * the gaufrette enabled validated file
 */
class PluginSfGaufretteValidatedFile extends sfValidatedFile
{
  protected
    $originalName = '',
    $tempName     = '',
    $savedName    = null,
    $type         = '',
    $size         = 0,
    $gaufrette    = null;

  /**
   * Constructor.
   *
   * @param string $originalName  The original file name
   * @param string $type          The file content type
   * @param string $tempName      The absolute temporary path to the file
   * @param int    $size          The file size (in bytes)
   * @param string $path          The path to save the file (optional).
   */
  public function __construct($originalName, $type, $tempName, $size, $gaufrette)
  {
    $this->originalName = $originalName;
    $this->tempName = $tempName;
    $this->type = $type;
    $this->size = $size;
    $this->gaufrette = $gaufrette;
  }

  /**
   * Saves the uploaded file.
   *
   * This method can throw exceptions if there is a problem when saving the file.
   *
   * If you don't pass a file name, it will be generated by the generateFilename method.
   * This will only work if you have passed a path when initializing this instance.
   *
   * @param  string $file      The file path to save the file
   * @param  int    $fileMode  The octal mode to use for the new file
   * @param  bool   $create    Indicates that we should make the directory before moving the file
   * @param  int    $dirMode   The octal mode to use when creating the directory
   *
   * @return string The filename without the $this->path prefix
   *
   * @throws Exception
   */
  public function save($file = null, $fileMode = 0666, $create = true, $dirMode = 0777)
  {
    if (null === $file)
    {
      $file = $this->generateFilename();
    }

    if ($content = file_get_contents($this->getTempName()))
    {
      $this->gaufrette->write($file, $content);
      $this->savedName = $file;
    }

    return $file;
  }
} // END OF PluginSfGaufretteValidatedFile