<?php

class sfGaufretteConfigHander extends sfYamlConfigHandler
{
  public function execute($configFiles)
  {
    $gaufrettes = self::getConfiguration($configFiles);

    $code = array();
    $code[] = '<?php';
    $code[] = '// auto-generated by '.__CLASS__;
    $code[] = '// date: '.date('Y/m/d H:is');
    $code[] = 'class sfGaufretteConfig';
    $code[] = '{';
    $code[] = '  static public $gaufrettes = '.var_export($gaufrettes, true).';';
    $code[] = '}';

    return implode(PHP_EOL, $code);
  }

  /** 
   * Returns the configuration for the current config handler.
   *
   * @param array $configFiles An array of ordered configuration files
   */
  public static function getConfiguration(array $configFiles)
  {
    return self::replaceConstants(self::flattenConfigurationWithEnvironment(
      self::parseYamls($configFiles)
    ));
  }

  /** 
   * Merges default, all and current environment configurations.
   *
   * @param array $config The main configuration array
   *
   * @return array The merged configuration                                                                
   */
  public static function flattenConfigurationWithEnvironment($config)
  {
    return array_merge(
      isset($config['default']) && is_array($config['default']) ? $config['default'] : array(),
      isset($config['all']) && is_array($config['all']) ? $config['all'] : array(),
      isset($config[sfConfig::get('sf_environment')]) && is_array($config[sfConfig::get('sf_environment')]) ? $config[sfConfig::get('sf_environment')] : array()
    );  
  }
}